### ISSUE TITLE
Filenames for transcript exons vs. ORF exons

### ISSUE THREAD

**Issue by bmmalone** [dieterich-lab/riboseq-utils#1]
This is directly connected to dieterich-lab/rp-bp#59. Any fix there will need to involve `ribo_filenames`.

**Comment by eboileau** [comment]
For the ORFs file, as flag `is_orf` has been added to `riboutils.ribo_filenames.get_exons` to differentiate between *exons* and *orfs* files, particularly in cases where there is no `note`. Added to riboseq-utils version **0.2.6** and rp-bp version **1.1.11**. This issue is now resolved.
