### ISSUE TITLE
Sampling syntax for pystan changed

### ISSUE THREAD

**Issue by bmmalone** [dieterich-lab/riboseq-utils#7]
There seems to have been a change in the interface for sampling in Stan version 2.17.0.0 that makes it incompatible with the current syntax in `estimate_metagene_profile_bayes_factors.py`. An easy fix is to update the requirements file to specify version 2.16.0.0. It would be better to update the calls in the code to work with the new version of stan.

**Comment by bmmalone** [comment]
As a very temporary fix, just fallback to the old version of pystan:
```
pip3 install pystan==2.16.0.0
```

**Comment by bmmalone** [comment]
The current version (0.2.5) uses the hack-ish approach of just specifying the old version in the requirements.txt file.

**Comment by eboileau** [comment]
Fixed and updated to pystan==2.19.0.0.
